{
  config,
  pkgs,
  inputs,
  lib,
  ...
}: {
  imports = [
    inputs.nix-openclaw.homeManagerModules.openclaw
  ];

  programs.openclaw = {
    # Path to managed documents directory
    documents = /home/hwan/code/openclaw-local/documents;

    # config = {
    #   gateway = {
    #     mode = "local";
    #     auth = {
    #       # Gateway authentication token
    #       token = "xcV3qOFmoXlqU8rsIgimxfMwImFF9X4z";
    #     };
    #   };
    #
    #   channels = {
    #     telegram = {
    #       # Path to Telegram bot token file
    #       tokenFile = "/home/hwan/.secrets/telegram-bot-token";
    #       # Your Telegram user ID from @userinfobot
    #       allowFrom = [1078515864];
    #       groups = {
    #         "*" = {requireMention = true;};
    #       };
    #     };
    #   };
    # };

    instances.default = {
      enable = true;
      plugins = [];
    };

    # Enable first-party plugins
    bundledPlugins = {
      summarize.enable = true;
      oracle.enable = true;
    };
  };

  sops.secrets."api-keys/anthropic" = {};

  sops.templates."openclaw.env".content = ''
    ANTHROPIC_API_KEY=${config.sops.placeholder."api-keys/anthropic"}
  '';

  # Create a custom config file to bypass the empty one generated by the module
  home.file.".openclaw/my-config.json".text = builtins.toJSON {
    gateway = {
      mode = "local";
      auth = {
        token = "xcV3qOFmoXlqU8rsIgimxfMwImFF9X4z";
      };
    };
    channels = {
      telegram = {
        tokenFile = "/home/hwan/.secrets/telegram-bot-token";
        allowFrom = [1078515864];
        groups = {
          "*" = {requireMention = true;};
        };
      };
    };
  };

  # Enable auto-start on login and override config path
  systemd.user.services.openclaw-gateway = {
    Install.WantedBy = ["default.target"];
    Service = {
      EnvironmentFile = config.sops.templates."openclaw.env".path;
      Environment = lib.mkForce [
        "HOME=%h"
        "OPENCLAW_CONFIG_PATH=%h/.openclaw/my-config.json"
        "OPENCLAW_STATE_DIR=%h/.openclaw"
        "OPENCLAW_NIX_MODE=1"
      ];
    };
  };
}
